spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/college-management-system?createDatabaseIfNotExist=true
    username: root
    password:
