spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/college-management-system?createDatabaseIfNotExist=true
    username: root
    password:
  security:
    user:
      name: user
      password: 721087c4-0ede-407e-8c1f-ac57e531f292